# Bakes a glyph atlas from the Arcade's ui_font.ttf into a C header.
#
# DOOM's menus live in a 320x200-lineage framebuffer that is magnified ~5.4x to
# the panel, so both the FreeDoom menu art and the 8px font arrive soft. The menu
# overlay draws text at native panel resolution instead; this supplies the
# glyphs. Same technique as bake_labels.py, widened to a full character set.
#
# One horizontal strip, alpha = coverage, RGB = white (tinted at draw time).
from PIL import Image, ImageDraw, ImageFont

FONT = "/home/geektrading/godot-mvp/proj/ui_font.ttf"
OUT  = "/home/geektrading/crispy-doom/src/android_glyphs.h"
SIZE = 64
CHARS = (" ABCDEFGHIJKLMNOPQRSTUVWXYZ"
         "abcdefghijklmnopqrstuvwxyz"
         "0123456789"
         ".,:;!?'\"()[]-/%+<>=*#_ ")
CHARS = "".join(dict.fromkeys(CHARS))   # de-dup, keep order

def rle(data):
    out = bytearray(); i = 0; n = len(data)
    while i < n:
        v = data[i]; c = 1
        while i + c < n and data[i + c] == v and c < 255:
            c += 1
        out.append(c); out.append(v); i += c
    return bytes(out)

f = ImageFont.truetype(FONT, SIZE)
probe = ImageDraw.Draw(Image.new("L", (8, 8)))

# common baseline/height so glyphs line up
asc, desc = f.getmetrics()
H = asc + desc
# Cap height, measured off "H". The DOOM side matches its own glyph height
# to this, so a line of text sits exactly where the engine laid it out.
hb = f.getbbox("H")
CAP = hb[3] - hb[1]

metrics = []
total_w = 0
for ch in CHARS:
    adv = int(round(probe.textlength(ch, font=f)))
    w = max(adv, 1)
    metrics.append([ch, total_w, w, adv])
    total_w += w

strip = Image.new("L", (total_w, H), 0)
d = ImageDraw.Draw(strip)
for ch, x, w, adv in metrics:
    d.text((x, 0), ch, font=f, fill=255)

packed = rle(strip.tobytes())

with open(OUT, "w") as o:
    o.write("//\n// Glyph atlas baked from the Arcade's ui_font.ttf.\n")
    o.write("// Generated by android/tools/bake_glyphs.py -- do not hand-edit.\n//\n\n")
    o.write("#ifndef ANDROID_GLYPHS_H\n#define ANDROID_GLYPHS_H\n\n")
    o.write("#define GLYPH_ATLAS_W %d\n#define GLYPH_ATLAS_H %d\n" % (total_w, H))
    o.write("#define GLYPH_COUNT   %d\n" % len(metrics))
    o.write("#define GLYPH_ASCENT %d\n" % asc)
    o.write("#define GLYPH_CAPHEIGHT %d\n\n" % CAP)
    o.write("typedef struct { char ch; short x, w, adv; } glyph_t;\n\n")
    o.write("static const glyph_t glyph_tab[GLYPH_COUNT] = {\n")
    for ch, x, w, adv in metrics:
        esc = {"'": "\\'", "\\": "\\\\", '"': '\\"'}.get(ch, ch)
        o.write("    { '%s', %d, %d, %d },\n" % (esc, x, w, adv))
    o.write("};\n\n")
    o.write("static const unsigned char glyph_rle[] = {\n")
    for i in range(0, len(packed), 16):
        o.write("    " + ",".join("0x%02x" % b for b in packed[i:i+16]) + ",\n")
    o.write("};\n\n#define GLYPH_RLE_LEN %d\n\n#endif\n" % len(packed))

print("atlas %dx%d, %d glyphs, raw=%d rle=%d bytes"
      % (total_w, H, len(metrics), total_w * H, len(packed)))
