from PIL import Image, ImageDraw, ImageFont

FONT = "/home/geektrading/godot-mvp/proj/ui_font.ttf"
OUT  = "/home/geektrading/crispy-doom/src/android_labels.h"
SIZE = 72
LABELS = ["L", "R", "START", "SELECT"]

def rle(data):
    out = bytearray(); i = 0; n = len(data)
    while i < n:
        v = data[i]; c = 1
        while i + c < n and data[i + c] == v and c < 255:
            c += 1
        out.append(c); out.append(v); i += c
    return bytes(out)

f = ImageFont.truetype(FONT, SIZE)
probe = ImageDraw.Draw(Image.new("L", (8, 8)))
blobs = []

for lab in LABELS:
    # stroke_width approximates Godot's variation_embolden=0.4 on the same face
    bb = probe.textbbox((0, 0), lab, font=f, stroke_width=2)
    w = bb[2] - bb[0]; h = bb[3] - bb[1]
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-bb[0], -bb[1]), lab, font=f, fill=255,
                             stroke_width=2, stroke_fill=255)
    blobs.append((lab, w, h, rle(img.tobytes())))

with open(OUT, "w") as o:
    o.write("//\n// Ghost-control labels, baked from the Arcade's ui_font.ttf so the\n")
    o.write("// lettering on L/R and START/SELECT matches the Arcade exactly.\n")
    o.write("// Generated by bake_labels.py -- do not hand-edit.\n//\n\n")
    o.write("#ifndef ANDROID_LABELS_H\n#define ANDROID_LABELS_H\n\n")
    o.write("typedef struct {\n    int w, h;\n    const unsigned char *rle;\n    int rlen;\n} atlabel_t;\n\n")
    for lab, w, h, data in blobs:
        o.write("static const unsigned char lbl_%s_data[] = {\n" % lab)
        for i in range(0, len(data), 16):
            o.write("    " + ",".join("0x%02x" % b for b in data[i:i+16]) + ",\n")
        o.write("};\n\n")
    o.write("enum { LBL_L, LBL_R, LBL_START, LBL_SELECT, LBL_NUM };\n\n")
    o.write("static const atlabel_t at_labels[LBL_NUM] = {\n")
    for lab, w, h, data in blobs:
        o.write("    { %d, %d, lbl_%s_data, %d },\n" % (w, h, lab, len(data)))
    o.write("};\n\n#endif\n")

for lab, w, h, data in blobs:
    print("%-7s %3dx%-3d raw=%-6d rle=%d" % (lab, w, h, w * h, len(data)))
